# Generated by Django 3.2 on 2022-05-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_time',
            new_name='time',
        ),
    ]
